### ISSUE TITLE
Put this project on Python Package Index

### ISSUE THREAD

**Issue by juanchristian** [smiley/steamapi#19]
Python Package Index (https://pypi.python.org/pypi)

It will be a lot easier for everyone using this API to have it on PyPI, so that people can easily install it using 'pip install steamapi'.

**Comment by superzazu** [comment]
Any news on this issue ? It'd be nice to just pip install the module :-)

**Comment by Socialery** [comment]
Probably worth mentioning that pypi does have 2 tags for unstable software

```
Development Status :: 2 - Pre-Alpha
Development Status :: 3 - Alpha
```

**Comment by LaoshuBaby** [comment]
About 10 years passed, is this package ready to be on PyPi?

**Comment by smiley** [comment]
@LaoshuBaby No, [because it’s no longer in active development](https://github.com/smiley/steamapi). It was a side project that got put aside over the years.
