### ISSUE TITLE
What are all the arguments steamapi.user.SteamUser() can take?

### ISSUE THREAD

**Issue by kevinthr** [smiley/steamapi#21]
I see that you can supply the argument userurl="smileybarry", ex: steamapi.user.SteamUser(userurl="smileybarry"), and also the 64 bit user id, ex: steamapi.user.SteamUser(76561197996416028, but the type of ID I want to supply is the one that shows in this format: STEAM_0:X:XXXXXX

I want to do this because that number basically reflects the timeframe in which the account was made, as these numbers are assigned incrementally. The thousandth Steam user would have SteamID STEAM_0:0:1000, I believe.

I can't find any further documentation on the arguments that can be supplied here. All I know is from the readme. Hope this makes sense.

**Comment by kevinthr** [comment]
Basically I am trying to find a way to choose randomly from all possibly existing steam accounts, or at least a great number of them.

**Comment by luizpericolo** [comment]
This post (
http://arstechnica.com/gaming/2014/04/introducing-steam-gauge-ars-reveals-steams-most-popular-games/)
says that:

"As detailed on the Steam Developer Wiki
<https://developer.valvesoftware.com/wiki/SteamID>, every individual user
on Steam gets a unique 64-bit SteamID that can be converted algorithmically
to a 17-digit decimal number, starting at 76561197960265729 and going up
sequentially from there. That’s why my profile page can also be accessed
using a URL in the
formhttp://steamcommunity.com/profiles/76561197980357107 (you
can find your own hidden SteamID number and Steam Community ID using this
site <http://steamidfinder.com/>; if you get results in the form of
"STEAM_0:X:XXXXXX," put those results through again for the URL-able ID).

Currently, the range of valid Steam Community IDs extends to include about
172 million pages (with some small gaps of invalid IDs occasionally popping
up in the middle). Theoretically, if we could look at every one of those
profile pages, we would have a comprehensive list of every game owned by
every Steam user."
You could choose a value between 76561197960265729 and (76561197960265729 +
172000000). You should notice that not all ids are valid, as the site says
and some steam profiles are not public, so you won't get any data from the
api.

I hope this helps.

Cheers,

________________________________
--
Luiz Felipe da Costa Pericolo Barbosa
UFRJ - Ciência da Computação / Computer Science
"Are you suggesting coconuts migrate?"
"Stay hungry. Stay foolish."
