### ISSUE TITLE
Retrieve tags of games

### ISSUE THREAD

**Issue by GigaDark** [smiley/steamapi#34]
Do you know way to get tags from steam page of game? Can you add this?

**Comment by smiley** [comment]
_(moved the question above from the title to the description)_

**Comment by smiley** [comment]
Not that I know of. It's probably part of the Big Picture private API (see #13), which is currently not implemented by this. (Due to being private & undocumented)

**Comment by smiley** [comment]
Closing this for now, but if you have any other questions about this, feel free to re-open the issue :)
