### ISSUE TITLE
How can I install steamapi?

### ISSUE THREAD

**Issue by Bastax13** [smiley/steamapi#35]
I'm beginner python programmer and it's some troubles with install...
I tried some ways to install it, but it doesn't installed.
Can you write a command (and in README too, I think) to install `steamapi`?

**Comment by mattbox** [comment]
Unfortunately this package isn't available through pip, you need to install it manually.

1. Download the package directly, and unzip.
2. From terminal cd into the folder.
3.  type `python setup.py install`

That should work, you might need to use `sudo python setup.py install` depending on how python is setup on your computer

**Comment by amrasmin** [comment]
Thank you mattbox this solved my problem.

**Comment by Bastax13** [comment]
Thanks!

**Comment by mankoell** [comment]
`sudo pip2 install git+https://github.com/smiley/steamapi.git`
