### ISSUE TITLE
APIPrivate error thrown when querying a SteamUser

### ISSUE THREAD

**Issue by BenQuigley** [smiley/steamapi#40]
What am I doing wrong here?

    >>> import steamapi
    >>> steamapi.core.APIConnection(api_key="my API key")
    # object gets created 
    >>> steamapi.user.SteamUser(userurl='my userid`)
    steamapi.errors.APIPRIVATE
`

**Comment by BenQuigley** [comment]
This URL (from [their docs](https://developer.valvesoftware.com/wiki/Steam_Web_API)) works, so I don't think the problem is with my Steam profile:

http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=[my API key]&steamids=[my steam ID]

**Comment by smiley** [comment]
Can you copy the exact code you ran (minus your key)?

**Comment by BenQuigley** [comment]
That is the exact code I ran, from the readme. (I left out the last '>>>' on the steamapiuser.SteamUser call; that was my input and this was the result:

```
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 15, in main
    steamapi.user.SteamUser(userurl=steam[1])
  File "c:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\s
teamapi-0.1-py3.5.egg\steamapi\user.py", line 118, in __init__
    response = APIConnection().call("ISteamUser", "ResolveVanityURL", "v0001", v
anityurl=userurl)
  File "c:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\s
teamapi-0.1-py3.5.egg\steamapi\core.py", line 437, in call
    errors.check(response)
  File "c:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\s
teamapi-0.1-py3.5.egg\steamapi\errors.py", line 106, in check
    raise APIPrivate()
steamapi.errors.APIPrivate
```

**Comment by smiley** [comment]
Well, it works on my end... Creating a `APIConnection` doesn't do anything server-side, so it could just be a bad key.

You can try creating an `APIInterface` and setting `autopopulate` to `True` to make it query the API itself:

```python
steamapi.core.APIInterface(self, api_key="<KEY>", autopopulate=False)
```

It looks like passing an invalid key here fails the call. (With a `APIPrivate` error, so that might be the issue)

**Comment by smiley** [comment]
I just added (44466353424061461a6e97c43d79b704a5f8ade1) key validation to `APIConnection` and `APIInterface`. Can you try it again, but with `validate_key=True` in `APIConnection`?

**Comment by smiley** [comment]
Did you reopen Python? (And ran `setup.py install` again if that's how you installed it)

**Comment by BenQuigley** [comment]
Oh, I did not re-run the setup tool, one second.

**Comment by smiley** [comment]
Ah, see that's what I don't like about `setup.py install` (vs `setup.py develop`). It copies the `.py` files to your `site-packages`, making changes to the source folder useless. `develop` is more suited to a `git clone` (which just links to the code instead of copying it).

**Comment by BenQuigley** [comment]
After re-running setup, errors out with three exceptions:
```
AttributeError: 'Singleton' object has no attribute '_instance'
steamapi.errors.APIPrivate: You have no permission to use this API, or your key may be invalid.
steamapi.errors.APIConfigurationError: This API key is invalid.
```
I have checked the API key, and it's exactly what is posted in my https://steamcommunity.com/dev/apikey page.

**Comment by smiley** [comment]
What triggers those exceptions? Can you please attach stack traces?

**Comment by BenQuigley** [comment]
With `validate_key=False`:

`C:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\python.exe C:/Users/BenQuigley/Dropbox/Projects/steamgames/main.py
Traceback (most recent call last):
  File "C:/Users/BenQuigley/Dropbox/Projects/steamgames/main.py", line 19, in <module>
    main()
  File "C:/Users/BenQuigley/Dropbox/Projects/steamgames/main.py", line 15, in main
    me = steamapi.user.SteamUser(userurl=steam[1])
  File "C:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\steamapi-0.1-py3.5.egg\steamapi\user.py", line 118, in __init__
    response = APIConnection().call("ISteamUser", "ResolveVanityURL", "v0001", vanityurl=userurl)
  File "C:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\steamapi-0.1-py3.5.egg\steamapi\core.py", line 459, in call
    errors.check(response)
  File "C:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\steamapi-0.1-py3.5.egg\steamapi\errors.py", line 107, in check
    raise APIPrivate("You have no permission to use this API, or your key may be invalid.")
steamapi.errors.APIPrivate: You have no permission to use this API, or your key may be invalid.

Process finished with exit code 1
`

**Comment by smiley** [comment]
```
Traceback (most recent call last):
  File "C:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\steamapi-0.1-py3.5.egg\steamapi\decorators.py", line 111, in __call__
    return self._instance
AttributeError: 'Singleton' object has no attribute '_instance'
```

This is normal and happens when no `APIConnection` was initialized yet. (Even on first-init, the `Singleton` class tries to look for an existing one)

```
Traceback (most recent call last):
  File "C:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\steamapi-0.1-py3.5.egg\steamapi\core.py", line 408, in __init__
    self.call("ISteamWebAPIUtil", "GetSupportedAPIList", "v1")
  File "C:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\steamapi-0.1-py3.5.egg\steamapi\core.py", line 459, in call
    errors.check(response)
  File "C:\Users\BenQuigley\AppData\Local\Programs\Python\Python35\lib\site-packages\steamapi-0.1-py3.5.egg\steamapi\errors.py", line 107, in check
    raise APIPrivate("You have no permission to use this API, or your key may be invalid.")
steamapi.errors.APIPrivate: You have no permission to use this API, or your key may be invalid.
```

This is later caught by the `validate_key=True` flow and translated into a `APIConfigurationError` (the third exception).

It still looks like an API issue, and since it doesn't occur with my own key, it feels like an issue with your API key. Can you try to revoke & regenerate the key? I've had rare cases where Steam Community denied the same key `steamcommunity.com/dev` gave me. Regenerating would fix that.

**Comment by BenQuigley** [comment]
That's a good idea. Thanks for the troubleshooting help.

**Comment by BenQuigley** [comment]
Same error, though. I feel like this is probably something simple that I'm doing wrong... The API key is expected as a string, right?

**Comment by smiley** [comment]
Yeah... [Can you send me your key privately via Discord?](https://discord.gg/XQDzf) (All API keys are read-only, anyway)

**Comment by BenQuigley** [comment]
It's working now; I think this must have been my user error. Thanks smiley.
