### ISSUE TITLE
Adding pleyerstats attribute to a game entity.

### ISSUE THREAD

**Issue by theSimplex** [smiley/steamapi#43]
Currently, a lot of information dropped out of GetUserStatsForGame response. Only achievements are used.
But there is more useful information for some games in 'playerstats'.

Was trying to create a pull request with that tweak :)

**Comment by smiley** [comment]
This is a pretty old Steamworks feature that most games don't use nowadays; I think I've only seen older Valve games make use of it. (TF2 etc.) What games did you plan to use this for?

**Comment by luckydonald** [comment]
I always get `500 Internal Server Error`...

**Comment by luckydonald** [comment]
@smiley Is it fixed now?

**Comment by smiley** [comment]
No, I don't know what issue you're even having (500 error on what?) and this ticket is for a completely different thing. Plus the API itself is working fine as far as I can tell.
