### ISSUE TITLE
Can't retrieve info for certain users

### ISSUE THREAD

**Issue by ScrappyCocco** [smiley/steamapi#45]
Can't understand why, the api download everyone else's steam information but if i ask my account info the api give some errors as:

``` 
\steamapi\decorators.py", line 67, in __get__
    value, last_update = inst._cache[self.__name__]
AttributeError: 'SteamApp' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

\steamapi\errors.py", line 107, in check
    raise APIPrivate("You have no permission to use this API, or your key may be invalid.")
steamapi.errors.APIPrivate: You have no permission to use this API, or your key may be invalid.

```

I already tried with my Id64 instead of Profile URL Id, can't understand where is the problem

This is a copy of the full error log:
[FullError.txt](https://github.com/smiley/steamapi/files/999428/FullError.txt)

**Comment by smiley** [comment]
What's your Steam ID/URL?

**Comment by ScrappyCocco** [comment]
ScrappyEnterprise / 76561198122939353 (Check the ID if you want, should be correct)

**Comment by smiley** [comment]
Kind of a really late response, but I've looked at it now and I can fetch that profile with my API key... Did you change your privacy settings since then?

**Comment by ScrappyCocco** [comment]
No, i never changed my privacy settings. And yes i can get my profile without errors since a long time.
My best hypothesis is that when i opened the issue i was playing a beta, that was doing something like "hiding" a game from the "recently played" list, and that maybe caused an error in the api...
