### ISSUE TITLE
Easy way to access a games tags

### ISSUE THREAD

**Issue by BronxBombers** [smiley/steamapi#48]
Hi, first off I want to thank you for this great tool you have created, it has helped me immensely with my current project I am working on! However, I noticed that you are missing a feature that however very specific, was a major roadblock in the development of my project. I needed a way to quickly access the tags for a specified list of games, and I couldn't find any way to do that with your interface or anything on the web. So in order to fix this I created a python script that created a database file of all games on steam and their tags. I plan on either hosting off my computer, or some free random hosting service, this database in an easily accessible way for use in my project, and think it could be a valuable addition to your tool to be able to add the tags of a game to its steamapp object. Here is a link to the code that creates the db https://github.com/BronxBombers/Steam-Tags-Database if you are interested in adding this to your project let me know and I can give you a link to wherever I decide to host it to, and I could also code the implementation to your system for you if ya wanted.

**Comment by smiley** [comment]
Sorry for the late response. It looks really cool, but I'm refraining from adding any undocumented APIs or scraped data to this project. It's meant to be a faithful implementation of Valve's documented -- or at least public -- web API. For the same reason, `steamapi` doesn't actually offer store browsing/searching. (the only stable API available is the private one used by Big Picture mode, which wasn't merged into the repo for the reason above)
