### ISSUE TITLE
Cannot get friends list

### ISSUE THREAD

**Issue by helsyQ** [smiley/steamapi#50]
Using this code, i can get user name, user level, but can't get user's friends list, getting error `steamapi.errors.APIUnauthorized: This API is not accessible to you.`
```
import steamapi
from steamapi import core, user

steamapi.core.APIConnection(api_key="<api key>", validate_key=True)

print(steamapi.user.SteamUser(<steamid>)

steam_user = user.SteamUser(userid=<steamid>)

print(steam_user.level)
print(steam_user.friends)
```

**Comment by helsyQ** [comment]
Actually, found a way to fix it by setting profile status to open. But how can i get list of ongoing invites to friends ?

**Comment by smiley** [comment]
You can't get any info that isn't public, like friend requests/invites. Only profile data and some game stats. (E.g.: achievements)
