### ISSUE TITLE
Search for Steam game by name

### ISSUE THREAD

**Issue by superloach** [smiley/steamapi#51]
Do you think you could either implement a game search function or an array of all games? (preferably the former, for speed :stuck_out_tongue_closed_eyes:)

Wasn't able to find it using `dir(steamapi.app)`, but I apologize if it's already there... although this is in desperate need of documentation.

**Comment by ScrappyCocco** [comment]
You can create your own pretty fast, or look [how i did mine](https://github.com/ScrappyCocco/ScroccoDiscordBot/blob/master/botGamingApi.py#L247)  😄
