### ISSUE TITLE
Can't Get The User's Description or Summary

### ISSUE THREAD

**Issue by xXWilliamXx** [smiley/steamapi#59]
I can't find a way to retrieve the user's description (or Summary) on their profile.

**Comment by rtizzy** [comment]
@xXWilliamXx 

I'm taking a look at the Steam API documentation and from what I can tell, there is no part of the public API that allows fetching that data. 

If you have some documentation for grabbing that from the API, give me a link and I'll take a look. 

I checked through:

https://partner.steamgames.com/doc/webapi/IPlayerService
https://partner.steamgames.com/doc/webapi/ISteamUser

**If it's not part of the public API:**

You may be able to accomplish this by:

1. Grabbing the profile URL with steamapi
2. Fetching that URL and grabbing just the portion you need.

**Comment by smiley** [comment]
Seems like only the (apparently deprecated) XML API offers this:
https://partner.steamgames.com/documentation/community_data

However, this project aims to just implement the new JSON-based "Web API", and I don't want to add abstraction endpoints for the older XML API. Though, if you need anything from it like summaries it seems simple enough: just add another by-steamid HTTP request to your code, basically querying the user's community URL with an extra `?xml=1`.
